local Misc = {
	sassInclude = { fg = C.purple },
	cssStringQQ = { fg = C.dark_red },
  sassClassChar = { fg = C.darker_red },
	sassClass = { fg = C.darker_red },
	sassProperty = { fg = C.red },
	cssProp = { fg = C.red },
	cssFunctionName = { fg = C.brown },
	cssCustomProp = { fg = C.red },
	cssColor = { fg = C.vivid_blue },
	cssUnitDecorators = { fg = C.dark_green },
	cssValueLength = { fg = C.dark_green },
  sassFunction = { fg = C.brown },
	sassCssAttribute = { fg = C.black },
	cssValueNumber = { fg = C.dark_green },
	cssPositioningAttr = { fg = C.vivid_blue },
	sassMixing = { fg = C.purple },
	sassMixinName = { fg = C.brown },
	cssTagName = { fg = C.darker_red },
	cssUIProp = { fg = C.darker_red },
	cssPseudoClassId = { fg = C.darker_red },
	cssPseudoClass = { fg = C.darker_red },
  cssValueTime = { fg = C.dark_green },
  cssValueAngle = { fg = C.dark_green },
  sassVariable = { fg = C.red },
  sassInterpolationDelimiter = { fg = C.dark_blue },

	sassDefinition = { fg = C.dark_green },
	sassAmpersand = { fg = C.red },
	cssPageProp = { fg = C.red },

	diffAdded = { fg = C.sign_add },
	diffRemoved = { fg = C.sign_delete },
	diffFileId = { fg = C.blue, style = "bold,reverse" },
	diffFile = { fg = C.alt_bg },
	diffNewFile = { fg = C.green },
	diffOldFile = { fg = C.red },
	debugPc = { bg = C.search_blue },
	debugBreakpoint = { fg = C.red, style = "reverse" },
	CodiVirtualText = { fg = C.hint_blue },
	SniprunVirtualTextOk = { fg = C.hint_blue },
	SniprunFloatingWinOk = { fg = C.hint_blue },
	SniprunVirtualTextErr = { fg = C.error_red },
	SniprunFloatingWinErr = { fg = C.error_red },
	CompeDocumentation = { bg = C.alt_bg },
	DapBreakpoint = { fg = C.error_red },
	xmlTag = { fg = C.cyan },
	xmlTagName = { fg = C.cyan },
	xmlEndTag = { fg = C.cyan },
	yamlPlainScalar = { fg = C.orange },
	yamlTSField = { fg = C.blue },
	luaFunc = { fg = C.yellow },
	luaFunction = { fg = C.blue },
	htmlH1 = { fg = C.fg },
	htmlH2 = { fg = C.fg },
	htmlH3 = { fg = C.fg },
	htmlH4 = { fg = C.fg },
	htmlH5 = { fg = C.fg },
	htmlH6 = { fg = C.fg },
	htmlHead = { fg = C.fg },
	htmlTitle = { fg = C.fg },
	htmlArg = { fg = C.light_blue },
	htmlTag = { fg = C.blue },
	htmlTagN = { fg = C.blue },
	htmlTagName = { fg = C.blue },
	htmlComment = { fg = C.green },
	htmlLink = { fg = C.orange, style = "underline" },
	cssBraces = { fg = C.fg },
	cssInclude = { fg = C.purple },
	cssClassName = { fg = C.yellow_orange },
	cssPseudoClassLang = { fg = C.yellow_orange },
	cssIdentifier = { fg = C.yellow_orange },
	cssDefinition = { fg = C.light_blue },
	cssAttrRegion = { fg = C.orange },
	cssFunction = { fg = C.purple },
	cssVendor = { fg = C.orange },
	cssStyle = { fg = C.light_blue },
	cssImportant = { fg = C.blue },
	jsonKeyword = { fg = C.light_blue },
	yamlBlockMappingKey = { fg = C.blue },
}

return Misc
