local Treesitter = {
	TSInclude = { fg = C.purple},
	TSPunctBracket = { fg = C.black},
	TSConstructor = { fg = C.dark_blue},
	TSVariable = { fg = C.dark_blue },
	TSString = { fg = C.dark_red},
	TSKeyword = { fg = C.blue, style = "italic" },
	TSFunction = { fg = C.brown },

	TSParameter = { fg = C.white },
	TSOperator = { fg = C.red, style = "bold,italic" },
	TSTagDelimiter = { fg = C.white },
	TSTagAttribute = { fg = C.orange },
	TSTag = { fg = C.red },
	TSNONE = { fg = C.white },
	TSConditional = { fg = C.blue },

	TSKeywordFunction = { fg = C.blue, style = "bold,italic" },
	TSKeywordReturn = { fg = C.red },
	TSComment = { fg = C.gray },
	TSProperty = { fg = C.blue },
	TSBoolean = { fg = C.purple },
	TSNumber = { fg = C.purple },
	TSVariableBuiltin = { fg = C.white },
	TSMethod = { fg = C.green },
	TSPunctSpecial = { fg = C.red },
	TSConstant = { fg = C.white },
	TSRepeat = { fg = C.red },

	cppTSKeyword = { fg = C.red, style = "italic" },
	cppTSNamespace = { fg = C.green },
	cppTSType = { fg = C.blue, style = "italic" },
	cppTSOperator = { fg = C.red, style = "bold,italic" },
	cppTSVariable = { fg = C.white },
	cppTSConstant = { fg = C.white },
	cppTSConstMacro = { fg = C.red },

	pythonTSVariable = { fg = C.white },
	pythonTSConstant = { fg = C.purple },
	pythonTSType = { fg = C.green },
	pythonTSVariableBuiltin = { fg = C.orange, style = "italic" },
	pythonTSField = { fg = C.white },
	pythonTSKeywordFunction = { fg = C.blue, style = "italic" },
	pythonTSOperator = { fg = C.red },

	luaTSFuncBuiltin = { fg = C.blue },
	luaTSFunction = { fg = C.blue },
	luaTSField = { fg = C.white },

	TSAnnotation = { fg = C.yellow },
	TSAttribute = { fg = C.cyan },
	TSType = { fg = C.cyan },
	TSTypeBuiltin = { fg = C.blue },
	TSException = { fg = C.purple },
	TSLabel = { fg = C.light_blue },
	TSNamespace = { fg = C.cyan },
	TSConstBuiltin = { fg = C.vivid_blue },
	TSFloat = { fg = C.light_green },
	TSCharacter = { fg = C.orange },
	TSError = { fg = C.error_red },
	TSFuncBuiltin = { fg = C.yellow },
	TSConstMacro = { fg = C.cyan },
	TSFuncMacro = { fg = C.yellow },
	TSField = { fg = C.light_blue },
	TSParameterReference = { fg = C.light_blue },
	TSSymbol = { fg = C.light_blue },
	TSText = { fg = C.fg },
	TSPunctDelimiter = { fg = C.fg },
	TSStringRegex = { fg = C.orange },
	TSStringEscape = { fg = C.yellow_orange },
	TSEmphasis = { style = "italic" },
	TSUnderline = { style = "underline" },
	TSTitle = { fg = C.fg },
	TSLiteral = { fg = C.orange },
	TSURI = { fg = C.orange, style = "underline" },
	TSKeywordOperator = { fg = C.blue },
	TSStructure = { fg = C.light_blue },
	TSStrong = { fg = C.blue, style = "bold" },
	TSQueryLinterError = { fg = C.warning_orange },
	TreesitterContext = { bg = C.tree_gray },
}

return Treesitter
