local Treesitter = {
	TSInclude = { fg = C.red },
	TSPunctBracket = { fg = C.white },
	TSConstructor = { fg = C.dark_green },
	TSString = { fg = C.green },
	TSKeyword = { fg = C.red, style = "italic" },
	TSKeywordFunction = { fg = C.blue },
	TSFunction = { fg = C.yellow },
	TSKeywordReturn = { fg = C.red, style = "italic" },
	TSTagDelimiter = { fg = C.light_green },
	TSTag = { fg = C.cyan },
	TSTagAttribute = { fg = C.yellow },
	TSOperator = { fg = C.cyan },
	TSNone = { fg = C.fg },
	TSBoolean = { fg = C.pink },
	TSVariable = { fg = C.light_green },
	TSConditional = { fg = C.red },

	TSParameter = { fg = C.yellow },
	TSComment = { fg = C.gray },
	TSProperty = { fg = C.blue },
	TSType = { fg = C.light_purple },
	TSConstant = { fg = C.yellow },
	TSURI = { fg = C.green, style = "underline" },
	TSText = { fg = C.white },
	TSNumber = { fg = C.orange },
	TSNamespace = { fg = C.dark_green },
	TSFuncBuiltin = { fg = C.dark_green },
	TSVariableBuiltin = { fg = C.red },
	TSMethod = { fg = C.blue },

	TSAnnotation = { fg = C.yellow },
	TSAttribute = { fg = C.cyan },
	TSTypeBuiltin = { fg = C.blue },
	TSException = { fg = C.purple },
	TSLabel = { fg = C.light_blue },
	TSRepeat = { fg = C.purple },
	TSConstBuiltin = { fg = C.vivid_blue },
	TSFloat = { fg = C.light_green },
	TSCharacter = { fg = C.orange },
	TSError = { fg = C.error_red },
	TSConstMacro = { fg = C.cyan },
	TSFuncMacro = { fg = C.yellow },
	TSField = { fg = C.light_blue },
	TSParameterReference = { fg = C.light_blue },
	TSSymbol = { fg = C.light_blue },
	TSPunctDelimiter = { fg = C.light_cyan },
	TSPunctSpecial = { fg = C.blue },
	TSStringRegex = { fg = C.orange },
	TSStringEscape = { fg = C.yellow_orange },
	TSEmphasis = { style = "italic" },
	TSUnderline = { style = "underline" },
	TSTitle = { fg = C.fg },
	TSLiteral = { fg = C.orange },
	TSKeywordOperator = { fg = C.blue },
	TSStructure = { fg = C.light_blue },
	TSStrong = { fg = C.blue, style = "bold" },
	TSQueryLinterError = { fg = C.warning_orange },
	TreesitterContext = { bg = C.tree_gray },

	cppTSInclude = { fg = C.green },
	cppTSString = { fg = C.light_green },
	cppTSKeyword = { fg = C.red },
	cppTSNamespace = { fg = C.yellow },
	cppTSType = { fg = C.red },
	cppTSVariable = { fg = C.white },
	pythonTSConstant = { fg = C.pink },
	pythonTSVariable = { fg = C.fg },
	pythonTSType = { fg = C.fg },
	pythonTSVariableBuiltin = { fg = C.light_green },
	pythonTSKeywordFunction = { fg = C.red },
	pythonTSConstructor = { fg = C.cyan },
	pythonTSParameter = { fg = C.light_green },
	pythonTSField = { fg = C.fg },
	pythonTSMethod = { fg = C.light_green },
	pythonTSRepeat = { fg = C.red },
	pythonTSComment = { fg = C.gray },
	pythonTSString = { fg = C.green },
	pythonTSException = { fg = C.red },
	pythonTSFuncBuiltin = { fg = C.yellow },
	pythonTSKeywordOperator = { fg = C.red },
	pythonTSConstBuiltin = { fg = C.pink },
	javascriptTSProperty = { fg = C.fg },
}

return Treesitter
